channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  - python=3.10.12         # https://pyreadiness.org/3.9/

  - pip=22.3                 # https://pip.pypa.io/en/stable/news/
  - pip:
      - pandas
      - loguru
      - rpaframework==23.0.0